from typing import Protocol
from uuid import UUID

from app_diagnosis.domain.execution import AgentRun, ToolRun


class AgentExecutionRepository(Protocol):
    async def add_agent_run(self, run: AgentRun) -> None: ...

    async def update_agent_run(self, run: AgentRun) -> None: ...

    async def get_agent_run(self, run_id: UUID) -> AgentRun | None: ...

    async def list_agent_runs(self, diagnosis_id: UUID) -> tuple[AgentRun, ...]: ...

    async def add_tool_run(self, run: ToolRun) -> None: ...

    async def list_tool_runs(self, agent_run_id: UUID) -> tuple[ToolRun, ...]: ...
